// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdtD_n0hYL0yD4EZSny5261nKCozoJF7k',
    appId: '1:708440783116:web:d6d6161be2359d02aaf129',
    messagingSenderId: '708440783116',
    projectId: 'chatalgr2',
    authDomain: 'chatalgr2.firebaseapp.com',
    storageBucket: 'chatalgr2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7K6JIgrHJAfjn5zm6VQp5cpKAzsFsvUc',
    appId: '1:708440783116:android:603518aa879c05c6aaf129',
    messagingSenderId: '708440783116',
    projectId: 'chatalgr2',
    storageBucket: 'chatalgr2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIBmmYGTiLckJa4rwQzVTRvG67kVA0aVY',
    appId: '1:708440783116:ios:b282173c866731d3aaf129',
    messagingSenderId: '708440783116',
    projectId: 'chatalgr2',
    storageBucket: 'chatalgr2.appspot.com',
    iosClientId:
        '708440783116-ci0a4eem7a8k5pm258hsp4uaskc35i5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIBmmYGTiLckJa4rwQzVTRvG67kVA0aVY',
    appId: '1:708440783116:ios:b282173c866731d3aaf129',
    messagingSenderId: '708440783116',
    projectId: 'chatalgr2',
    storageBucket: 'chatalgr2.appspot.com',
    iosClientId:
        '708440783116-ci0a4eem7a8k5pm258hsp4uaskc35i5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatal',
  );
}
