// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9CUCUpVQX_WFHrmgJnPGRfaN7jCO5qqc',
    appId: '1:509916028147:web:4b6481232a5a6fdbabeb86',
    messagingSenderId: '509916028147',
    projectId: 'pureleaf-first-firebase',
    authDomain: 'pureleaf-first-firebase.firebaseapp.com',
    storageBucket: 'pureleaf-first-firebase.appspot.com',
    measurementId: 'G-EK4W7QXRE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALEaWIxYtIBgslOqbx09zqtH6WyvAEAzo',
    appId: '1:509916028147:android:84795e9b8b98d90fabeb86',
    messagingSenderId: '509916028147',
    projectId: 'pureleaf-first-firebase',
    storageBucket: 'pureleaf-first-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAow_Pmn0PRaBJ7kE_M1Uzgs4fkSCk3Lms',
    appId: '1:509916028147:ios:b2f631dbdb65f946abeb86',
    messagingSenderId: '509916028147',
    projectId: 'pureleaf-first-firebase',
    storageBucket: 'pureleaf-first-firebase.appspot.com',
    iosClientId: '509916028147-or5n8plf8orto5u2b0qm5j8lp6t59jme.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePersonnelle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAow_Pmn0PRaBJ7kE_M1Uzgs4fkSCk3Lms',
    appId: '1:509916028147:ios:b2f631dbdb65f946abeb86',
    messagingSenderId: '509916028147',
    projectId: 'pureleaf-first-firebase',
    storageBucket: 'pureleaf-first-firebase.appspot.com',
    iosClientId: '509916028147-or5n8plf8orto5u2b0qm5j8lp6t59jme.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePersonnelle',
  );
}
